### ISSUE TITLE
/bin/scan_alignment not found

### ISSUE THREAD

**Issue by vendig** [bioinform/neusomatic#1]
Hi. Congratulations on the tool. I installed the tool and at the moment trying to do some testing. I encountered a problem. I am not IT expert, therefore would be grateful for some additional help.
I am running it on Databrick and also on Mac computer and both times the same problem appeared.

The command line:
%sh
/databricks/python/bin/python /local_disk0/neu/neusomatic-master/neusomatic/python/preprocess.py \
--mode call \
--reference /dbfs/FileStore/tables/ucsc.hg19.chr20.unittest.fasta \
--region_bed /dbfs/FileStore/tables/test_nist_b37_chr20_100kbp_at_10mb-f8b09.bed \
--tumor_bam /dbfs/FileStore/tables/NA12878_S1_chr20_10_10p1mb-41bf7.bam \
--normal_bam /dbfs/FileStore/tables/NA12878_S1_chr20_10_10p1mb-41bf7.bam \
--work work_train \
--scan_alignments_binary ../bin/scan_alignments

Error:
INFO 2018-09-06 11:25:01,741 __main__             Namespace(dbsnp_to_filter=None, del_merge_min_af=0, del_min_af=0.05, ensemble_tsv=None, good_ao=10, ins_merge_min_af=0, ins_min_af=0.05, long_read=False, matrix_base_pad=7, matrix_width=32, merge_r=0.5, min_ao=1, min_dp=5, min_ev_frac_per_col=0.06, min_mapq=1, mode='call', normal_bam='/dbfs/FileStore/tables/NA12878_S1_chr20_10_10p1mb-41bf7.bam', num_threads=1, reference='/dbfs/FileStore/tables/ucsc.hg19.chr20.unittest.fasta', region_bed='/dbfs/FileStore/tables/test_nist_b37_chr20_100kbp_at_10mb-f8b09.bed', restart=False, scan_alignments_binary='../bin/scan_alignments', scan_maf=0.01, scan_window_size=2000, skip_without_qual=False, snp_min_af=0.05, snp_min_ao=3, snp_min_bq=10, truth_vcf=None, tsv_batch_size=50000, tumor_bam='/dbfs/FileStore/tables/NA12878_S1_chr20_10_10p1mb-41bf7.bam', work='work_train')
INFO 2018-09-06 11:25:01,743 __main__             -----------------------------------------------------------
INFO 2018-09-06 11:25:01,743 __main__             Postprocessing
INFO 2018-09-06 11:25:01,743 __main__             -----------------------------------------------------------
INFO 2018-09-06 11:25:01,743 __main__             Scan tumor bam (first without quality scores).
INFO 2018-09-06 11:25:01,744 __main__             Scan bam.
INFO 2018-09-06 11:25:01,744 scan_alignments      -----------------------------------------------------------
INFO 2018-09-06 11:25:01,744 scan_alignments      Scan Alignment BAM
INFO 2018-09-06 11:25:01,744 scan_alignments      -----------------------------------------------------------
INFO 2018-09-06 11:25:02,151 utils                Running command: ['../bin/scan_alignments', '--ref', '/dbfs/FileStore/tables/ucsc.hg19.chr20.unittest.fasta', '-b', '/dbfs/FileStore/tables/NA12878_S1_chr20_10_10p1mb-41bf7.bam', '-L', 'work_train/work_tumor_without_q/region_0.bed', '--out_vcf_file', 'work_train/work_tumor_without_q/work.0/candidates.vcf', '--out_count_file', 'work_train/work_tumor_without_q/work.0/count.bed', '--window_size', '2000', '--min_af', '0.01', '--min_mapq', '1', '--num_thread', '1']
ERROR 2018-09-06 11:25:02,155 scan_alignments      [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/local_disk0/neu/neusomatic-master/neusomatic/python/scan_alignments.py", line 120, in scan_alignments
    outputs = pool.map_async(run_scan_alignments, map_args).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/local_disk0/neu/neusomatic-master/neusomatic/python/preprocess.py", line 359, in <module>
    args.scan_alignments_binary)
  File "/local_disk0/neu/neusomatic-master/neusomatic/python/preprocess.py", line 208, in preprocess
    calc_qual=False, dbsnp_regions=[])
  File "/local_disk0/neu/neusomatic-master/neusomatic/python/preprocess.py", line 50, in process_split_region
    calc_qual=calc_qual)
  File "/local_disk0/neu/neusomatic-master/neusomatic/python/scan_alignments.py", line 126, in scan_alignments
    raise Exception
Exception

I was trying to find scan_alignments in bin folder but the folder is empty.
Thank you a lot for all help.

**Comment by roger-liu-bina** [comment]
@vendig Have you run `build.sh` before running `preprocess.py`?

**Comment by vendig** [comment]
Super, I run again build.sh and the problem was resolved. I am getting further error with first step.
Input is still the same as above but an error is different. There are no work.0 and count.bed directories after the command is run. 

**Ouput:**
ERROR 2018-09-06 21:26:38,542 scan_alignments      No such file '/local_disk0/neu/neusomatic-master/neusomatic/work_train/work_tumor_without_q/work.0/count.bed'
Traceback (most recent call last):
  File "/local_disk0/neu/neusomatic-master/neusomatic/python/scan_alignments.py", line 120, in scan_alignments
    outputs = pool.map_async(run_scan_alignments, map_args).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: No such file '/local_disk0/neu/neusomatic-master/neusomatic/work_train/work_tumor_without_q/work.0/count.bed'
Traceback (most recent call last):
  File "/local_disk0/neu/neusomatic-master/neusomatic/python/preprocess.py", line 359, in <module>
    args.scan_alignments_binary)
  File "/local_disk0/neu/neusomatic-master/neusomatic/python/preprocess.py", line 208, in preprocess
    calc_qual=False, dbsnp_regions=[])
  File "/local_disk0/neu/neusomatic-master/neusomatic/python/preprocess.py", line 50, in process_split_region
    calc_qual=calc_qual)
  File "/local_disk0/neu/neusomatic-master/neusomatic/python/scan_alignments.py", line 126, in scan_alignments
    raise Exception
Exception

**Then I tested only the function scan_alignments(). Input:**
scan_alignments(work="/local_disk0/neu/neusomatic-master/neusomatic/python/work_train", 
                scan_alignments_binary="/local_disk0/neu/neusomatic-master/neusomatic/bin/scan_alignments", 
                input_bam="/dbfs/FileStore/tables/NA12878_S1_chr20_10_10p1mb-41bf7.bam",
                regions_bed_file="/dbfs/FileStore/tables/test_nist_b37_chr20_100kbp_at_10mb-f8b09.bed", 
                reference="/dbfs/FileStore/tables/ucsc.hg19.chr20.unittest.fasta",
                num_threads=1, window_size=2000, maf=0.01, min_mapq=1, restart=True,
                split_region_files=[], calc_qual=True)


**And an output is:**
INFO 2018-09-06 21:34:34,332 scan_alignments      -----------------------------------------------------------
INFO 2018-09-06 21:34:34,332 scan_alignments      Scan Alignment BAM
INFO 2018-09-06 21:34:34,332 scan_alignments      -----------------------------------------------------------
INFO 2018-09-06 21:34:34,574 split_bed            -----------------------------------------------------------
INFO 2018-09-06 21:34:34,574 split_bed            Split region

INFO 2018-09-06 21:34:34,574 split_bed            -----------------------------------------------------------
INFO 2018-09-06 21:34:34,585 split_bed            Total length: 9010
INFO 2018-09-06 21:34:34,585 split_bed            Split 0: 9010
INFO 2018-09-06 21:34:34,585 split_bed            Total splitted length: 9010
ERROR 2018-09-06 21:34:35,189 scan_alignments      No such file '/local_disk0/neu/neusomatic-master/neusomatic/python/work_train/work.0/count.bed'
Traceback (most recent call last):
  File "/local_disk0/neu/neusomatic-master/neusomatic/python/scan_alignments.py", line 120, in scan_alignments
    outputs = pool.map_async(run_scan_alignments, map_args).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: No such file '/local_disk0/neu/neusomatic-master/neusomatic/python/work_train/work.0/count.bed'


Exception                                 Traceback (most recent call last)
<command-87617> in <module>()
      5                 reference="/dbfs/FileStore/tables/ucsc.hg19.chr20.unittest.fasta",
      6                 num_threads=1, window_size=2000, maf=0.01, min_mapq=1, restart=True,
----> 7                 split_region_files=[], calc_qual=True)



Please let me know what could be a problem. It would be incredibly helpful if you could also share testing datasets.
Thank you a lot.

**Comment by msahraeian** [comment]
@vendig I added a test example at https://github.com/bioinform/neusomatic#quick-test. 
Would you please try that and share the log if it failed? 
Please build again before test.

**Comment by vendig** [comment]
Yeah. Test example ran successfully. Perfect! Thank you a lot.
