### ISSUE TITLE
scan_alignments failed! when using "run_test.sh"

### ISSUE THREAD

**Issue by joonlee3** [bioinform/neusomatic#14]
Hi,

    I tried to run 'run_test.sh' to check if neusomatic works properly in my system. After installing the tool in my system and running the example code "run_test.sh", I've got the following error message. Would you please look into it? Thanks.

{0}: ./run_test.sh 
INFO 2018-10-08 11:46:31,584 __main__             Namespace(dbsnp_to_filter=None, del_merge_min_af=0, del_min_af=0.05, ensemble_tsv=None, good_ao=10, ins_merge_min_af=0, ins_min_af=0.05, long_read=False, matrix_base_pad=7, matrix_width=32, merge_r=0.5, min_ao=1, min_dp=5, min_ev_frac_per_col=0.06, min_mapq=10, mode='call', normal_bam='../normal.bam', num_threads=1, reference='Homo_sapiens.GRCh37.75.dna.chromosome.22.fa', region_bed='../region.bed', restart=False, scan_alignments_binary='/site/ne/app/x86_64/neusomatic/v0.1.1/neusomatic/bin/scan_alignments', scan_maf=0.05, scan_window_size=2000, skip_without_qual=False, snp_min_af=0.05, snp_min_ao=10.0, snp_min_bq=20.0, truth_vcf=None, tsv_batch_size=50000, tumor_bam='../tumor.bam', work='work_standalone')
INFO 2018-10-08 11:46:31,584 preprocess           ----------------------Preprocessing------------------------
INFO 2018-10-08 11:46:31,587 preprocess           Scan tumor bam (first without quality scores).
INFO 2018-10-08 11:46:31,589 process_split_region Scan bam.
INFO 2018-10-08 11:46:31,590 scan_alignments      -------------------Scan Alignment BAM----------------------
INFO 2018-10-08 11:46:31,612 split_region         ------------------------Split region-----------------------
INFO 2018-10-08 11:46:31,629 split_region         Total length: 40516
INFO 2018-10-08 11:46:31,639 split_region         Split 0: 40516
INFO 2018-10-08 11:46:31,639 split_region         Total splitted length: 40516
ERROR 2018-10-08 11:46:31,656 run_scan_alignments (PoolWorker-1) Traceback (most recent call last):
  File "/site/ne/app/x86_64/neusomatic/v0.1.1/python/scan_alignments.py", line 32, in run_scan_alignments
    raise IOError("File not found: {}".format(scan_alignments_binary))
IOError: File not found: /site/ne/app/x86_64/neusomatic/v0.1.1/neusomatic/bin/scan_alignments

ERROR 2018-10-08 11:46:31,656 run_scan_alignments (PoolWorker-1) File not found: /site/ne/app/x86_64/neusomatic/v0.1.1/neusomatic/bin/scan_alignments
ERROR 2018-10-08 11:46:31,658 __main__             Traceback (most recent call last):
  File "/site/ne/app/x86_64/neusomatic/v0.1.1/python/preprocess.py", line 389, in <module>
    args.scan_alignments_binary)
  File "/site/ne/app/x86_64/neusomatic/v0.1.1/python/preprocess.py", line 234, in preprocess
    calc_qual=False, dbsnp_regions=[])
  File "/site/ne/app/x86_64/neusomatic/v0.1.1/python/preprocess.py", line 50, in process_split_region
    calc_qual=calc_qual)
  File "/site/ne/app/x86_64/neusomatic/v0.1.1/python/scan_alignments.py", line 136, in scan_alignments
    raise Exception("scan_alignments failed!")
Exception: scan_alignments failed!

ERROR 2018-10-08 11:46:31,658 __main__             Aborting!
ERROR 2018-10-08 11:46:31,658 __main__             preprocess.py failure on arguments: Namespace(dbsnp_to_filter=None, del_merge_min_af=0, del_min_af=0.05, ensemble_tsv=None, good_ao=10, ins_merge_min_af=0, ins_min_af=0.05, long_read=False, matrix_base_pad=7, matrix_width=32, merge_r=0.5, min_ao=1, min_dp=5, min_ev_frac_per_col=0.06, min_mapq=10, mode='call', normal_bam='../normal.bam', num_threads=1, reference='Homo_sapiens.GRCh37.75.dna.chromosome.22.fa', region_bed='../region.bed', restart=False, scan_alignments_binary='/site/ne/app/x86_64/neusomatic/v0.1.1/neusomatic/bin/scan_alignments', scan_maf=0.05, scan_window_size=2000, skip_without_qual=False, snp_min_af=0.05, snp_min_ao=10.0, snp_min_bq=20.0, truth_vcf=None, tsv_batch_size=50000, tumor_bam='../tumor.bam', work='work_standalone')
Traceback (most recent call last):
  File "/site/ne/app/x86_64/neusomatic/v0.1.1/python/preprocess.py", line 395, in <module>
    raise e
Exception: scan_alignments failed!

**Comment by msahraeian** [comment]
@joonlee3, happy to see your interest in NeuSomatic. The error suggests that the binary file `/site/ne/app/x86_64/neusomatic/v0.1.1/neusomatic/bin/scan_alignments` does not exist. Please make sure you have successfully built the binaries using `./build.sh`.

**Comment by joonlee3** [comment]
@msahraeian Thank you for the quick reply. Yes, that was my silly mistake. After correcting it, I reran neusomatic and got the following error message - 

/site/ne/app/x86_64/neusomatic/v0.1.1/bin/scan_alignments: error while loading shared libraries: libmpi.so.40: cannot open shared object file: No such file or directory

Any suggestions/insights? Please let me know. Thank you.

Best,
Joon

**Comment by roger-liu-bina** [comment]
@joonlee3 Thanks for reporting the issue. Can you run `ldd /site/ne/app/x86_64/neusomatic/v0.1.1/bin/scan_alignments`? and show us the output?

**Comment by joonlee3** [comment]
@roger-liu-bina My colleague helped me resolve the issue. After fixing the problem. I ran neusomatic. Initially, it looked okay but shortly I've got another error message -
#On region chr12:? [6120762,6120910) 
#Aligned read number: 106
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551518) > this->size() (which is 74)

I am wondering what caused this problem.

**Comment by roger-liu-bina** [comment]
@joonlee3 This error usually means that you don't have MD tag in your alignment. Can you check you bam file for MD tag? See the required input part https://github.com/bioinform/neusomatic/blob/master/README.md
If that is the case, you just need to run

`samtools calmd -@ num_threads -b alignment.bam reference.fasta  > alignment.md.bam `
`samtools index alignment.md.bam`
