### ISSUE TITLE
Bed file from my bam file

### ISSUE THREAD

**Issue by sugyun** [bioinform/neusomatic#16]
Hi, I want to run my own bam files for variant calling.
And I have two questions.
1. How do I make bed file from my bam file? Do you have any recommand?  (ex bedtools bamtobed) which bam file (ref / normal / tumor) should I use?

2. If i use different bed file for calling, do I have to train the model again with different bed file?

Thanks!

**Comment by msahraeian** [comment]
@sugyun happy to see your interest in NeuSomatic. 

1- The bed file will specify the region you want to call or train your network on. If you don't have specific preferences, you can use the whole-genome as your target region. You can obtain such bed file using your reference `.fai` index file:
```
cat reference.fasta.fai | awk -F "\t" '{print $1 "\t0\t" $2}' | awk -F "\t" '$1 ~ /^(chr)?[0-9XYMT]+$/' > region.bed
```
2- It depends on your goal. In general if you train and call on the same region of same tumor/normal pair, you will cause overtraining. But, if you want to train on a tumor/normal pair sample and call on other samples, the regions used for training and calling can be the same.

**Comment by sugyun** [comment]
@msahraeian  Thank you for your quick reply! :> It works well. Thank you again.
