### ISSUE TITLE
RuntimeError: Expected object of type torch.DoubleTensor but found type torch.FloatTensor for argument #2 'weight'

### ISSUE THREAD

**Issue by jingmeng-bioinformatics** [bioinform/neusomatic#23]
Hi, I am running quick test, I got the following error:

INFO 2018-10-23 18:40:01,715 __main__             Namespace(dbsnp_to_filter=None, del_merge_min_af=0, del_min_af=0.05, ensemble_tsv=None, good_ao=10, ins_merge_min_af=0, ins_min_af=0.05, long_read=False, matrix_base_pad=7, matrix_width=32, max_dp=40000, merge_r=0.5, min_ao=1, min_dp=5, min_ev_frac_per_col=0.06, min_mapq=10, mode='call', normal_bam='../normal.bam', num_threads=1, reference='Homo_sapiens.GRCh37.75.dna.chromosome.22.fa', region_bed='../region.bed', restart=False, scan_alignments_binary='../../neusomatic/bin/scan_alignments', scan_maf=0.05, scan_window_size=2000, skip_without_qual=False, snp_min_af=0.05, snp_min_ao=10.0, snp_min_bq=20.0, truth_vcf=None, tsv_batch_size=50000, tumor_bam='../tumor.bam', work='work_standalone')
INFO 2018-10-23 18:40:01,716 preprocess           ----------------------Preprocessing------------------------
INFO 2018-10-23 18:40:01,716 preprocess           Scan tumor bam (first without quality scores).
INFO 2018-10-23 18:40:01,716 process_split_region Scan bam.
INFO 2018-10-23 18:40:01,716 scan_alignments      -------------------Scan Alignment BAM----------------------
INFO 2018-10-23 18:40:01,728 split_region         ------------------------Split region-----------------------
INFO 2018-10-23 18:40:01,742 split_region         Total length: 40516
INFO 2018-10-23 18:40:01,746 split_region         Split 0: 40516
INFO 2018-10-23 18:40:01,746 split_region         Total splitted length: 40516
INFO 2018-10-23 18:40:01,758 run_scan_alignments (PoolWorker-1) Running command: ['../../neusomatic/bin/scan_alignments', '--ref', 'Homo_sapiens.GRCh37.75.dna.chromosome.22.fa', '-b', '../tumor.bam', '-L', 'work_standalone/work_tumor_without_q/region_0.bed', '--out_vcf_file', 'work_standalone/work_tumor_without_q/work.0/candidates.vcf', '--out_count_file', 'work_standalone/work_tumor_without_q/work.0/count.bed', '--window_size', '2000', '--min_af', '0.05', '--min_mapq', '10', '--max_depth', '40000', '--num_thread', '1']
INFO 2018-10-23 18:40:02,894 process_split_region Filter candidates.
INFO 2018-10-23 18:40:02,898 filter_candidates (PoolWorker-2) ---------------------Filter Candidates---------------------
INFO 2018-10-23 18:40:02,937 preprocess           Scan tumor bam (and extracting quality scores).
INFO 2018-10-23 18:40:02,937 process_split_region Scan bam.
INFO 2018-10-23 18:40:02,938 scan_alignments      -------------------Scan Alignment BAM----------------------
INFO 2018-10-23 18:40:02,938 scan_alignments      split_regions to be used (will ignore region_bed): work_standalone/work_tumor_without_q/candidates_region_0.bed
INFO 2018-10-23 18:40:02,941 run_scan_alignments (PoolWorker-3) Running command: ['../../neusomatic/bin/scan_alignments', '--ref', 'Homo_sapiens.GRCh37.75.dna.chromosome.22.fa', '-b', '../tumor.bam', '-L', 'work_standalone/work_tumor_without_q/candidates_region_0.bed', '--out_vcf_file', 'work_standalone/work_tumor/work.0/candidates.vcf', '--out_count_file', 'work_standalone/work_tumor/work.0/count.bed', '--window_size', '2000', '--min_af', '0.05', '--min_mapq', '10', '--max_depth', '40000', '--num_thread', '1', '--calculate_qual_stat']
INFO 2018-10-23 18:40:03,184 process_split_region Filter candidates.
INFO 2018-10-23 18:40:03,190 filter_candidates (PoolWorker-4) ---------------------Filter Candidates---------------------
INFO 2018-10-23 18:40:03,202 preprocess           Scan normal bam (and extracting quality scores).
INFO 2018-10-23 18:40:03,202 process_split_region Scan bam.
INFO 2018-10-23 18:40:03,202 scan_alignments      -------------------Scan Alignment BAM----------------------
INFO 2018-10-23 18:40:03,203 scan_alignments      split_regions to be used (will ignore region_bed): work_standalone/work_tumor_without_q/candidates_region_0.bed
INFO 2018-10-23 18:40:03,211 run_scan_alignments (PoolWorker-5) Running command: ['../../neusomatic/bin/scan_alignments', '--ref', 'Homo_sapiens.GRCh37.75.dna.chromosome.22.fa', '-b', '../normal.bam', '-L', 'work_standalone/work_tumor_without_q/candidates_region_0.bed', '--out_vcf_file', 'work_standalone/work_normal/work.0/candidates.vcf', '--out_count_file', 'work_standalone/work_normal/work.0/count.bed', '--window_size', '2000', '--min_af', '0.2', '--min_mapq', '10', '--max_depth', '40000', '--num_thread', '1', '--calculate_qual_stat']
INFO 2018-10-23 18:40:03,395 preprocess           Generate dataset.
INFO 2018-10-23 18:40:03,395 preprocess           Dataset for region work_standalone/work_tumor_without_q/candidates_region_0.bed
INFO 2018-10-23 18:40:03,395 generate_dataset     ---------------------Generate Dataset----------------------
INFO 2018-10-23 18:40:03,404 generate_dataset     len_candids: 80
INFO 2018-10-23 18:40:03,405 split_region         ------------------------Split region-----------------------
INFO 2018-10-23 18:40:03,419 split_region         Total length: 2456
INFO 2018-10-23 18:40:03,421 split_region         Split 0: 2456
INFO 2018-10-23 18:40:03,421 split_region         Total splitted length: 2456
INFO 2018-10-23 18:40:03,425 find_records (PoolWorker-6) Start find_records for worker 0
INFO 2018-10-23 18:40:03,459 find_records (PoolWorker-6) N_none: 80 
INFO 2018-10-23 18:40:03,460 generate_dataset     Write 1/1 split to work_standalone/dataset/work.0/candidates_0.tsv for cnts (0..80)/80
INFO 2018-10-23 18:40:03,693 generate_dataset     Generating dataset is Done.
INFO 2018-10-23 18:40:03,693 preprocess           Preprocessing is Done.
INFO 2018-10-23 18:40:04,114 __main__             use_cuda: False
INFO 2018-10-23 18:40:04,114 call_neusomatic      -----------------Call Somatic Mutations--------------------
INFO 2018-10-23 18:40:04,124 call_neusomatic      Load pretrained model from checkpoint ../../neusomatic/models/NeuSomatic_v0.1.0_standalone_Dream3_70purity.pth
INFO 2018-10-23 18:40:04,126 call_neusomatic      tag: NeuSomatic_v0.1.0_standalone_Dream3_70purity
INFO 2018-10-23 18:40:04,128 call_neusomatic      Run for candidate files: ['work_standalone/dataset/work.0/candidates_0.tsv']
INFO 2018-10-23 18:40:04,128 dataloader           (1024, 1048576)
INFO 2018-10-23 18:40:04,128 dataloader           (524288, 1048576)
INFO 2018-10-23 18:40:04,128 dataloader           Len's of tsv files in this batch: [80]
INFO 2018-10-23 18:40:04,130 extract_info_tsv (MainProcess) Loaded 80 candidates for work_standalone/dataset/work.0/candidates_0.tsv
INFO 2018-10-23 18:40:04,131 call_neusomatic      N_dataset: 80
ERROR 2018-10-23 18:40:04,154 __main__             Traceback (most recent call last):
  File "../../neusomatic/python/call.py", line 529, in <module>
    use_cuda)
  File "../../neusomatic/python/call.py", line 466, in call_neusomatic
    net, vartype_classes, call_loader, out_dir, model_tag, use_cuda)
  File "../../neusomatic/python/call.py", line 63, in call_variants
    outputs, _ = net(matrices)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jingmeng/Desktop/neusomatic/neusomatic/python/network.py", line 67, in forward
    x = self.pool1(F.relu(self.bn1(self.conv1(x))))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: Expected object of type torch.DoubleTensor but found type torch.FloatTensor for argument #2 'weight'

ERROR 2018-10-23 18:40:04,155 __main__             Aborting!
ERROR 2018-10-23 18:40:04,155 __main__             call.py failure on arguments: Namespace(batch_size=100, candidates_tsv=['work_standalone/dataset/work.0/candidates_0.tsv'], checkpoint='../../neusomatic/models/NeuSomatic_v0.1.0_standalone_Dream3_70purity.pth', ensemble=False, lowqual_threshold=0.4, max_load_candidates=1000000, num_threads=1, out='work_standalone', pass_threshold=0.7, reference='Homo_sapiens.GRCh37.75.dna.chromosome.22.fa')
Traceback (most recent call last):
  File "../../neusomatic/python/call.py", line 534, in <module>
    raise e
RuntimeError: Expected object of type torch.DoubleTensor but found type torch.FloatTensor for argument #2 'weight'

How to fix the problem, please? Thank you!

**Comment by msahraeian** [comment]
@jingmeng-bioinformatics happy to see your interest in NeuSomatic. This error usually happens when your pytorch version is wrong. Please make sure you have installed pytorch v0.3.1 as well as other python packages as instructed in https://github.com/bioinform/neusomatic

**Comment by jingmeng-bioinformatics** [comment]
@msahraeian Thank you. I reinstalled the packages with conda as you suggest, and I can run neusomatic successfully.

**Comment by ozlemmuslu** [comment]
If you change the file neusomatic/neusomatic/python/network.py in line 67 from

`x = self.pool1(F.relu(self.bn1(self.conv1(x))))`

to

`x = self.pool1(F.relu(self.bn1(self.conv1(x.float()))))`

this exception is not raised in torch version 1.0.0
