### ISSUE TITLE
Supplementary materials for NeuSomatic paper

### ISSUE THREAD

**Issue by gunjanbaid** [bioinform/neusomatic#29]
Hello! Where can I find the supplementary materials for the NeuSomatic paper? They do not seem to be part of the PDF here: https://doi.org/10.1101/39380

**Comment by msahraeian** [comment]
Hi, for some reason the link is not shown there but you can find it at:

https://www.biorxiv.org/content/biorxiv/suppl/2018/09/04/393801.DC2/393801-1.pdf

**Comment by gunjanbaid** [comment]
Thank you!
