### ISSUE TITLE
Ensemble method error in preprocess.py & generate_dataset.py

### ISSUE THREAD

**Issue by smalysz1** [bioinform/neusomatic#37]
Hello!

I just had a quick question based on the error below, which I am getting when I try to use the ensemble mode of neusomatic. (I have had a good experience using the stand-alone method so first off I just want to say thanks for the great tool!)

Error:
    line 1350, in extract_ensemble:   s = ensemble_data[:, np.array(i_s)]
    IndexError: arrays used as indices must be of integer (or boolean) type

Some background: I am currently running a test of one sample where I have a matched tumor & normal bam files, in addition to mutect2, strelka2 (indels/SNV), and vardict vcf files. I have generated the ensemble_ann.tsv as described in the documentation but when providing it to the preprocess.py script, this error is thrown. 

The line of this error is from the generate_dataset.py script https://github.com/bioinform/neusomatic/blob/d2dd889c9deaa2ca8490496284f3e48fb381abd8/neusomatic/python/generate_dataset.py#L1350 
And so my question is that I'm hoping someone could explain and help me understand better, where and what the variable **"i_s"** is being defined as. 

I noticed earlier on in this function, that on the lines 1267 & 1268, float values are being appended to "ensemble_data" so I'm not sure if that has anything to do with the above error. I do think that understanding the **"i_s"** variable more could help me narrow down the source of my error, so if anyone has any suggestion or other opinions, they would be greatly appreciated!
https://github.com/bioinform/neusomatic/blob/d2dd889c9deaa2ca8490496284f3e48fb381abd8/neusomatic/python/generate_dataset.py#L1267

Thank you!
Stephanie

**Comment by msahraeian** [comment]
@smalysz1 Hi Stephanie, I am happy to see your interest in NeuSomatic. 
The `i_s` variable has indices of columns, and it is defined based on the first element in `enumerate(...)`, so it should be integer (for example you can see that in lines 1294-1323). 
I guess there should be something wrong with your `ensemble_ann.tsv` file. Would you please share with me the first few lines of your `ensemble_ann.tsv` file?

**Comment by smalysz1** [comment]
Hi, thanks for your fast reply! I was thinking something similar but it was hard for me to tell from the ensemble_ann.tsv file. I've attached the first few lines, please let me know if you see anything that could be causing that error. Thank you again!

[ensemble_ann_sub.txt](https://github.com/bioinform/neusomatic/files/3144461/ensemble_ann_sub.txt)

**Comment by msahraeian** [comment]
@smalysz1 
Please pull master and run again.
This issue should have been is fixed in #38.

**Comment by smalysz1** [comment]
Thank you so much! The fix has helped and I can run without errors; I appreciate all your help!
