### ISSUE TITLE
which validate script you use? 

### ISSUE THREAD

**Issue by LeiHaoa** [bioinform/neusomatic#66]
Hi,
 I wonder which validate script you use? 
 I evaluated different validate methods like hap.py/som.py and just compare [chorm-pos-alt-ref]，this two functions showed different results.
 So, I am curious about which validate script you use to test detect results and truth file and get recall/precision??

Thanks!

**Comment by msahraeian** [comment]
Hi @LeiHaoa ,
I think [hap.py](https://github.com/Illumina/hap.py) can give you precision and recall. 
I usually use either `hap.py` or [VarSim](https://github.com/bioinform/varsim), which you can run it as:
```
python compare_vcf.py \
--regions EVAL_REGION.BED \
--out_dir OUT \
--reference REF.fa \
--true_vcf TRUTH.VCF \
--vcfs PREDICTION.VCF 
```

**Comment by LeiHaoa** [comment]
thanks very much!
