### ISSUE TITLE
How to produce synthetic training data with different tumor purity and normal contamination ratio?

### ISSUE THREAD

**Issue by ZekunYin** [bioinform/neusomatic#69]
Hi,
Wonderful work! I think this is one of the most impressive works in the field of somatic mutation calling. I'm very interested in it. And I'd like to reproduce some evaluation results mentioned in your paper. But now I've problem in producing synthetic training data with different tumor purity and normal contamination ratio. It seems that this [link](https://github.com/bioinform/somaticseq/tree/master/utilities/dockered_pipelines/bamSimulator) didn't describe the details about producing training data with different tumor purity. I hope you can help me solve this problem.

Best,
Zekun

**Comment by msahraeian** [comment]
@ZekunYin Thanks for your interest in NeuSomatic. This [link](https://github.com/bioinform/somaticseq/tree/master/utilities/dockered_pipelines/bamSimulator) shows how you can spike mutations in a normal bam to generate a synthetic tumor bam with desired AFs. Once you have the simulated tumor, you can mix tumor and normal bams with different rations to generate mixed tumors/normals with different purities. For instance, using `picard DownsampleSam`, you can downsample tumor to 70% and normal to 30% and mix them with `picard mergesamfiles` to generate 70% pure tumors.

**Comment by ZekunYin** [comment]
That's very helpful! Thanks so much!
